# Generated by Django 2.0.2 on 2018-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_id', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_specific', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Index',
                'verbose_name_plural': 'Data Index',
                'db_table': 'dataset_index',
            },
        ),
    ]
