# Generated by Django 2.0.2 on 2018-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_local', models.DateField(blank=True, null=True)),
                ('area_id', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_id', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_specific', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 최고기온')),
                ('daily_temp_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 평균기온')),
                ('daily_temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 최저기온')),
                ('daily_rmh_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 평균 상대습도')),
                ('daily_rmh_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 최저 상대습도')),
                ('daily_precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 강수량')),
                ('daily_wind_speed_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 평균 풍속')),
                ('daily_accumulated_sunset', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='일 누적 일조시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '작물별 환경',
                'verbose_name_plural': '작물별 환경',
                'db_table': 'crop_environment',
            },
        ),
        migrations.AlterIndexTogether(
            name='cropenvironment',
            index_together={('date_local', 'area_id', 'crop_id')},
        ),
    ]
