# Generated by Django 2.0.2 on 2018-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180207_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamisIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kind_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('kind_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kaims Index',
                'verbose_name_plural': 'Kaims Index',
                'db_table': 'kamis_index',
            },
        ),
    ]
