# Generated by Django 2.0.2 on 2018-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180215_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamispriceinfo',
            name='market_class',
            field=models.CharField(blank=True, help_text='01:retail, 02:wholesale', max_length=100, null=True, verbose_name='도소매 구분'),
        ),
        migrations.AddField(
            model_name='kamispriceinfo',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='category_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대분류 코드'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대분류'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='품명 코드'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='품명'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='kind_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세부 품명'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='kind_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세부 품명'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='단위당 가격'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='quality_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='등급 코드'),
        ),
        migrations.AlterField(
            model_name='kamispriceinfo',
            name='quality_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='등급'),
        ),
    ]
