# Generated by Django 2.0.2 on 2018-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180215_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamispriceinfo',
            name='market_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시장명'),
        ),
        migrations.AddField(
            model_name='kamispriceinfo',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지역명'),
        ),
    ]
